name: "🏗 Setup"

inputs:
  runWebpack:
    description: "Run webpack build"
    default: false

runs:
  using: "composite"
  steps:
    # Checkout repo
    - uses: actions/checkout@v3
    # Setup node
    - uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "yarn"
    # Install node dependencies
    - run: yarn install --frozen-lockfile
      shell: bash
    # Webpack cache
    - uses: actions/cache@v3
      if: inputs.runWebpack
      with:
        path: node_modules/.cache/webpack/
        key: ${{ github.head_ref }}-webpack-build
        restore-keys: |
          main-webpack-build
    # Webpack build
    - run: yarn webpack:build
      if: inputs.runWebpack
      shell: bash
