name: "🏗 Setup"
description: ""
author: ""
inputs:
  runWebpack:
    description: "Run webpack build"
    required: false
runs:
  using: "composite"
  steps:
    # Checkout repo
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    # Setup node
    - uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "yarn"
    # Install node dependencies
    - run: yarn install --frozen-lockfile
      shell: bash
    # Webpack cache
    - uses: actions/cache@v3
      with:
        path: node_modules/.cache/webpack/
        key: ${{ github.head_ref }}-webpack-build
        restore-keys: |
          main-webpack-build
    # TEST
    - run: echo inputs.runWeback - ${{ inputs.runWeback }}
      shell: bash
    # Build repository
    - if: ${{ inputs.runWeback == true }}
      run: yarn webpack:build
      shell: bash
