on:
  workflow_call:
    secrets:
      PASSWORD:
        required: true
      SHOP:
        required: true
      IGNORED_FILES:
        required: false

env:
  BUILD_MANIFEST: assets/__manifest
  SHOPIFY_FLAG_PATH: dist
  SHOPIFY_FLAG_STORE: ${{ secrets.SHOP }}
  SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.PASSWORD }}

jobs:
  create_or_update:
    runs-on: ubuntu-latest
    if: github.event_name != 'closed' # TODO
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repo + setup node
        uses: Juno-Ecommerce/theme-actions/.github/actions/cache-and-install@main

      - name: Update (and create) preview theme
        uses: Juno-Ecommerce/theme-actions/.github/actions/theme-preview-create@main
        with:
          IGNORED_FILES: ${{ secrets.IGNORED_FILES }}

  delete:
    runs-on: ubuntu-latest
    if: github.event_name == 'closed' # TODO
    steps:
      - name: Delete preview theme
        uses: Juno-Ecommerce/theme-actions/.github/actions/theme-preview-delete@main
