on:
  workflow_call:
    secrets:
      PASSWORD:
        required: true
      SHOP:
        required: true
      IGNORED_FILES:
        required: false

env:
  CI: 1
  THEME_ROOT: dist
  BUILD_MANIFEST: assets/__manifest

jobs:
  create_or_update:
    runs-on: ubuntu-latest
    if: github.event_name != 'closed' # TODO
    env:
      SHOPIFY_PASSWORD: ${{ secrets.PASSWORD }}
      SHOPIFY_SHOP: ${{ secrets.SHOP }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repo + setup node
        uses: Juno-Ecommerce/theme-actions/.github/actions/cache-and-install@main

      - name: Setup Shopify CLI
        uses: Juno-Ecommerce/theme-actions/.github/actions/shopify-cli@main

      - name: Update (and create) preview theme
        uses: Juno-Ecommerce/theme-actions/.github/actions/theme-preview-create@main
        with:
          IGNORED_FILES: ${{ secrets.IGNORED_FILES }}

  delete:
    runs-on: ubuntu-latest
    if: github.event_name == 'closed' # TODO
    env:
      SHOPIFY_PASSWORD: ${{ secrets.PASSWORD }}
      SHOPIFY_SHOP: ${{ secrets.SHOP }}
    steps:
      - name: Delete preview theme
        uses: Juno-Ecommerce/theme-actions/.github/actions/theme-preview-delete@main
