name: "🧬 Theme preview"

on: workflow_call

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            :exclamation: **Create a Preview theme** :exclamation:
            To create a preview theme add `preview` to the labels on the right hand side
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"

  create-preview:
    runs-on: ubuntu-latest
    if: contains(github.event.*.labels.*.name, 'preview')
    steps:
      - uses: Juno-Ecommerce/theme-actions/.github/actions/setup@main
