name: "🧬 Theme preview"

on:
  workflow_call:
    secrets:
      PASSWORD:
        required: true
      STORE:
        required: true
      TOKEN:
        required: true

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            :exclamation: **Create a Preview theme** :exclamation:
            To create a preview theme add `preview` to the labels on the right hand side
          repo-token: ${{ secrets.TOKEN }}
          repo-token-user-login: "github-actions[bot]"

  create:
    runs-on: ubuntu-latest
    if: contains(github.event.*.labels.*.name, 'preview')
    steps:
      - uses: Juno-Ecommerce/theme-actions/.github/actions/setup@main
        with:
          runWebpack: "true"
      # - uses: Juno-Ecommerce/theme-actions/.github/actions/theme-preview@main
      #   with:
      #     ACTION: "CREATE_PREVIEW"
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #     SHOPIFY_PASSWORD: ${{ secrets.PASSWORD }}
      #     SHOPIFY_STORE: ${{ secrets.STORE }}

  # remove:
  #   runs-on: ubuntu-latest
  #   if: contains(github.event.*.labels.*.name, 'preview')
  #   steps:
  #     - uses: Juno-Ecommerce/theme-actions/.github/actions/setup@main
  #     - uses: Juno-Ecommerce/theme-actions/.github/actions/theme-preview@main
  #       with:
  #         ACTION: "REMOVE_PREVIEW"
  #         GITHUB_TOKEN: ${{ secrets.TOKEN }}
  #         SHOPIFY_PASSWORD: ${{ secrets.PASSWORD }}
  #         SHOPIFY_STORE: ${{ secrets.STORE }}
