on:
  workflow_call:
    secrets:
      PASSWORD:
        required: true
      STORE:
        required: true

env:
  GITHUB_TOKEN: ${{ github.token }}
  WORK_DIR: ${{ github.workspace }}
  BUILD_DIR: dist
  BUILD_MANIFEST: assets/__manifest.json

jobs:
  comment:
    runs-on: ubuntu-latest
    if: contains(github.event.*.labels.*.name, 'preview') == false && github.event_name != 'closed'
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            :exclamation: **Create a Preview theme** :exclamation:
            To create a preview theme add `preview` to the labels on the right hand side
          repo-token: ${{ env.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"

  create:
    runs-on: ubuntu-latest
    if: contains(github.event.*.labels.*.name, 'preview') && github.event_name != 'closed'
    steps:
      - uses: Juno-Ecommerce/theme-actions/.github/actions/setup@main
        with:
          runWebpack: true
      - uses: Juno-Ecommerce/theme-actions/.github/actions/theme-preview@main
        with:
          ACTION: "CREATE_PREVIEW"
          SHOPIFY_PASSWORD: ${{ secrets.PASSWORD }}
          SHOPIFY_STORE: ${{ secrets.STORE }}

  remove:
    runs-on: ubuntu-latest
    if: contains(github.event.*.labels.*.name, 'preview') && github.event_name == 'closed'
    steps:
      - uses: Juno-Ecommerce/theme-actions/.github/actions/theme-preview@main
        with:
          ACTION: "REMOVE_PREVIEW"
          SHOPIFY_PASSWORD: ${{ secrets.PASSWORD }}
          SHOPIFY_STORE: ${{ secrets.STORE }}
