on:
  workflow_call:
    secrets:
      PASSWORD:
        required: true
      SHOP:
        required: true
      THEME_ID:
        required: true

env:
  CI: 1
  THEME_ROOT: dist
  BUILD_MANIFEST: assets/__manifest

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SHOPIFY_PASSWORD: ${{ secrets.PASSWORD }}
      SHOPIFY_SHOP: ${{ secrets.SHOP }}
      SHOPIFY_THEME_ID: ${{ secrets.THEME_ID }}
    steps:
      - name: Create GitHub deployment
        id: deployment
        uses: altinukshini/deployment-action@releases/v1
        with:
          token: ${{ github.token }}
          environment: production

      - name: Checkout repo + setup node
        uses: Juno-Ecommerce/theme-actions/.github/actions/cache-and-install@main
        with:
          build: true

      - name: Setup Shopify CLI
        uses: Juno-Ecommerce/theme-actions/.github/actions/shopify-cli@main

      - name: Update deployment status (Inprogress)
        uses: altinukshini/deployment-status@v1.0.1
        with:
          token: ${{ github.token }}
          state: "in_progress"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          description: "Deploying code for branch: "

      - name: Deploy theme
        uses: Juno-Ecommerce/theme-actions/.github/actions/theme-deploy@main

      - name: Update deployment status (success)
        if: success()
        uses: altinukshini/deployment-status@v1.0.1
        with:
          token: ${{ github.token }}
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: altinukshini/deployment-status@v1.0.1
        with:
          token: ${{ github.token }}
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
