on: workflow_call

env:
  BUILD_MANIFEST: assets/__manifest
  SHOPIFY_FLAG_PATH: dist

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: Juno-Ecommerce/theme-actions/.github/actions/cache-and-install@main

      - name: Lint
        run: pnpm run lint

  theme-check:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: Juno-Ecommerce/theme-actions/.github/actions/cache-and-install@main
        with:
          build: true

      - name: Theme check
        run: pnpm shopify theme check
