on:
  workflow_call:
    secrets:
      PASSWORD:
        required: true
      SHOP:
        required: true
      IGNORED_FILES:
        required: false

env:
  SHOPIFY_CLI_NO_ANALYTICS: true
  BUILD_MANIFEST: assets/__manifest
  SHOPIFY_FLAG_PATH: ${{ github.workspace }}/dist

jobs:
  create_or_update:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      SHOPIFY_FLAG_STORE: ${{ secrets.SHOP }}
      SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.PASSWORD }}
    steps:
      - name: Prepare
        uses: Juno-Ecommerce/theme-actions/.github/actions/cache-and-install@main

      - name: Update (+ create) preview theme
        uses: Juno-Ecommerce/theme-actions/.github/actions/theme-preview-create@main
        with:
          build: true
          IGNORED_FILES: ${{ secrets.IGNORED_FILES }}
